//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressMaster
    {
        public int AddressMasterID { get; set; }
        public string MapaCityCode { get; set; }
        public Nullable<int> MapaStreetCode { get; set; }
        public string HouseNumber { get; set; }
        public string iGoCityCode { get; set; }
        public string iGoStreetCode { get; set; }
        public string Entrance { get; set; }
        public string MapiCityCode { get; set; }
        public string MapiStreetCode { get; set; }
        public string MapiBuildingID { get; set; }
        public string Yad2CityCode { get; set; }
        public Nullable<int> Yad2StreetCode { get; set; }
        public string Yad2AreaCode { get; set; }
        public string Shchuna { get; set; }
        public string LamasStat { get; set; }
        public string MapiBuildingCenterX { get; set; }
        public string MapiBuildingCenterY { get; set; }
        public string verticalX { get; set; }
        public string verticalY { get; set; }
        public string Gush { get; set; }
        public string Chelka { get; set; }
    
        public virtual iGoCity iGoCity { get; set; }
        public virtual iGoStreet iGoStreet { get; set; }
        public virtual MapaCity MapaCity { get; set; }
        public virtual MapaStreet MapaStreet { get; set; }
        public virtual MapiCity MapiCity { get; set; }
        public virtual MapiStreet MapiStreet { get; set; }
        public virtual Yad2Area Yad2Area { get; set; }
        public virtual Yad2City Yad2City { get; set; }
    }
}
