//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class iGoStreet
    {
        public iGoStreet()
        {
            this.AddressMaster = new HashSet<AddressMaster>();
        }
    
        public string iGoStreetCodeID { get; set; }
        public string iGoStreetCode { get; set; }
        public string iGoStreetName { get; set; }
        public string iGoCityCode { get; set; }
        public string iGoCityName { get; set; }
    
        public virtual ICollection<AddressMaster> AddressMaster { get; set; }
    }
}
