//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listings
    {
        public int ID { get; set; }
        public string Address { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> StreetID { get; set; }
        public Nullable<short> HouseNumber { get; set; }
        public string City { get; set; }
        public string CityCode { get; set; }
        public Nullable<int> Price { get; set; }
        public string Shchuna { get; set; }
        public Nullable<int> ShchunaID { get; set; }
        public Nullable<int> IsSold { get; set; }
        public Nullable<int> IsFromAgent { get; set; }
        public Nullable<int> IsFirstHand { get; set; }
        public Nullable<int> PicRef { get; set; }
        public Nullable<int> Rooms { get; set; }
        public Nullable<decimal> SqMeter { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SP_GEOMETRY { get; set; }
    
        public virtual Municipalities Municipalities { get; set; }
        public virtual Neighborhoods Neighborhoods { get; set; }
        public virtual Streets Streets { get; set; }
    }
}
