//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapaCity
    {
        public MapaCity()
        {
            this.AddressMaster = new HashSet<AddressMaster>();
            this.MapaStreet = new HashSet<MapaStreet>();
        }
    
        public string MapaCityCode { get; set; }
        public string MapaCityName { get; set; }
    
        public virtual ICollection<AddressMaster> AddressMaster { get; set; }
        public virtual ICollection<MapaStreet> MapaStreet { get; set; }
    }
}
