//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapiStreet
    {
        public MapiStreet()
        {
            this.AddressMaster = new HashSet<AddressMaster>();
        }
    
        public string MapiStreetCode { get; set; }
        public string MapiStreetName { get; set; }
        public string MapiCityCode { get; set; }
    
        public virtual MapiCity MapiCity { get; set; }
        public virtual ICollection<AddressMaster> AddressMaster { get; set; }
    }
}
