//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapiCity
    {
        public MapiCity()
        {
            this.AddressMaster = new HashSet<AddressMaster>();
            this.MapiStreet = new HashSet<MapiStreet>();
        }
    
        public string MapiCityCode { get; set; }
        public string MapiCityName { get; set; }
    
        public virtual ICollection<AddressMaster> AddressMaster { get; set; }
        public virtual ICollection<MapiStreet> MapiStreet { get; set; }
    }
}
