//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipalities
    {
        public Municipalities()
        {
            this.Listings = new HashSet<Listings>();
            this.Streets = new HashSet<Streets>();
        }
    
        public string MunicipalName { get; set; }
        public string MunicipalCode { get; set; }
        public string MunicipalNameENG { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SP_GEOMETRY { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual ICollection<Listings> Listings { get; set; }
        public virtual ICollection<Streets> Streets { get; set; }
    }
}
