//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schools
    {
        public short objid { get; set; }
        public string institutename { get; set; }
        public Nullable<int> SchoolRank { get; set; }
        public string cityname { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string Shchuna { get; set; }
        public Nullable<int> ShchunaID { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SP_GEOMETRY { get; set; }
    }
}
