//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Streets
    {
        public Streets()
        {
            this.Listings = new HashSet<Listings>();
        }
    
        public int ID { get; set; }
        public string Street { get; set; }
        public string CityName { get; set; }
        public string CityCode { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SP_GEOMETRY { get; set; }
    
        public virtual Municipalities Municipalities { get; set; }
        public virtual ICollection<Listings> Listings { get; set; }
    }
}
