//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yad2Area
    {
        public Yad2Area()
        {
            this.AddressMaster = new HashSet<AddressMaster>();
        }
    
        public string Yad2AreaCode { get; set; }
        public string Yad2AreaName { get; set; }
    
        public virtual ICollection<AddressMaster> AddressMaster { get; set; }
    }
}
