//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yad2_TA_BuildingPoints_Updated
    {
        public string MapiStreetCode1 { get; set; }
        public string MapiStreetCode2 { get; set; }
        public string STR_NAME1 { get; set; }
        public Nullable<short> HOUSE_NO { get; set; }
        public string ENTRY { get; set; }
        public Nullable<short> LOCALITY_I { get; set; }
        public string LOCALITY_N { get; set; }
        public Nullable<int> ID { get; set; }
        public string address1 { get; set; }
        public Nullable<short> house_num_1 { get; set; }
        public Nullable<short> house_num_1_2 { get; set; }
        public Nullable<short> house_num_1_3 { get; set; }
        public Nullable<short> house_num_1_4 { get; set; }
        public Nullable<short> house_num_1_5 { get; set; }
        public Nullable<short> house_num_1_6 { get; set; }
        public string address2 { get; set; }
        public Nullable<short> house_num_2 { get; set; }
        public Nullable<short> house_num_2_2 { get; set; }
        public Nullable<short> house_num_2_3 { get; set; }
        public Nullable<short> house_num_2_4 { get; set; }
        public Nullable<short> house_num_2_5 { get; set; }
        public Nullable<short> house_num_2_6 { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<short> ID_2 { get; set; }
        public Nullable<short> City_Code { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public Nullable<decimal> Building_X { get; set; }
        public Nullable<decimal> Building_Y { get; set; }
        public Nullable<decimal> StreetView_X { get; set; }
        public Nullable<decimal> StreetView_Y { get; set; }
        public int MI_PRINX { get; set; }
    }
}
