//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yad2Street
    {
        public int Yad2StreetID { get; set; }
        public string Yad2StreetCode { get; set; }
        public string Yad2StreetName { get; set; }
        public string Yad2CityCode { get; set; }
        public string Yad2CityName { get; set; }
    
        public virtual Yad2City Yad2City { get; set; }
    }
}
