//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yad2.Demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yad2City
    {
        public Yad2City()
        {
            this.AddressMaster = new HashSet<AddressMaster>();
            this.Yad2Street = new HashSet<Yad2Street>();
        }
    
        public string Yad2CityCode { get; set; }
        public string Yad2CityName { get; set; }
    
        public virtual ICollection<AddressMaster> AddressMaster { get; set; }
        public virtual ICollection<Yad2Street> Yad2Street { get; set; }
    }
}
